### ISSUE TITLE
Discussion about shared reducers with adrian

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/frontend-conventions#1]
adrian [5:41 AM] 
http://blog.javascripting.com/2016/02/02/encapsulation-in-redux/
JavaScripting
Encapsulation in Redux: the Right Way to Write Reusable Components
Redux is one of the most discussed JavaScript front-end technologies. It has defined few paradigms that vastly improve developer efficiency and give us a solid foundation for building apps in a simple yet robust way. No framework is perfect though, and even Redux has its drawbacks. Redux has the special
Feb 2nd at 3:57 PM
## Written by

Tomas Weiss

(1MB)

[5:43] 
TLDR: having multiple reducers respond to one action introduces tight coupling and makes it harder to get an overall view of what the effect of a single action is

[5:43] 
we started doing this when we introduced normalizr

[5:43] 
@julian ^

julian [5:43 AM] 
hm

[5:45] 
I’ll read that when I get to it thanks

[5:46] 
so hold on

[5:46] 
what if we just had a simple rule:

[5:46] 
`Only use 1 constant in one reducer` (edited)

[5:47] 
although

[5:47] 
tbh

[5:47] 
I’m not sure if what we’re doing is so bad right now

[5:48] 
it’s mostly fetch actions we’re talking about

adrian [5:48 AM] 
yeah

[5:48] 
true

[5:48] 
but right now for example

[5:48] 
the Environments reducer needs to listen to the `FETCH_RUN` action

[5:48] 
since some environment data is included there

julian [5:49 AM] 
hm

[5:49] 
yea

[5:49] 
I disliked that when I saw it but couldn’t put my finger on it

[5:50] 
I think it makes sense to actions, reducer and component should be a coherent `one`

[5:50] 
Cause actions are the API to update a component after all

adrian [5:51 AM] 
y

julian [5:51 AM] 
so basically

[5:51] 
instead of listening to foreign action types (edited)

[5:51] 
we just dispatch the appropriate action inside `fetchRun`

[5:52] 
hm

adrian [5:52 AM] 
Initially I came to that conclusion

julian [5:52 AM] 
but then you still have coupling

adrian [5:52 AM] 
but you're just moving the tight coupling to the action creator

julian [5:52 AM] 
only reversed

adrian [5:52 AM] 
y

[5:52] 
http://www.code-experience.com/problems-with-flux/#reducersdonotsolvetheproblems
The Code Experience
Problems with Flux
I have been writing React/Flux applications for a year now. Looking back at one year of Flux development I can clearly say that this Flux thing works. Past are the days of "I'm not touching that event chain". All the Flux codebases I have worked on were clean, debuggable
July 28th, 2015 at 7:44 PM
## Written by

Reto Schläpfer

[5:52] 
suggests slicing the reducers in a different way

[5:53] 
slice by action

[5:55] 
instead of writing a reducer for every "state slice", write a reducer for every action

julian [5:55 AM] 
hm

adrian [5:56 AM] 
and then inside that single reducer you can compose multiple complex operations defined in separate modules

[5:56] 
this moves the coupling up

[5:56] 
i think it's less intuitive but maybe it's because I read the redux guide first ¯_(ツ)_/¯

julian [5:57 AM] 
redux is super unopinionated

[5:58] 
Let’s step back

[5:58] 
what are we worried about?

adrian [5:58 AM] 
for me it's 2 things

[5:59] 
tight coupling between modules but more importantly, needing to `grep SOME_ACTION` and read multiple files to understand fully what `SOME_ACTION` does (edited)

julian [6:00 AM] 
is that a problem that you’re facing right now?

[6:00] 
or just a worry that should this become a thing we’ll have this problem?

adrian [6:00 AM] 
not for the writer, but for the reader/reviewer

julian [6:00 AM] 
ok

[6:00] 
so right now

[6:01] 
I think that’s exactly one of the reasons why constants are `CONSTANTS`. They are global, unique, easy to search for, they ​_stand out_​

[6:02] 
easy to search for (edited)

adrian [6:03 AM] 
so our approach is at least better than coupling the action creators

julian [6:03 AM] 
well

[6:03] 
we still do couple action creators a fair bit

[6:03] 
tbh

adrian [6:04 AM] 
true

julian [6:04 AM] 
so let’s talk about module boundaries

[6:04] 
If this was the perfect app

[6:05] 
you could just pull out a module (consisting of reducer, actions and component)

[6:05] 
And not break the module or the app

[6:05] 
That’s be a real module correct?

adrian [6:05 AM] 
y

julian [6:06 AM] 
It would:

[6:06] 
1 - Resolve the worry of coupling

[6:06] 
2 - Make things a ton easier to refactor

[6:06] 
3 - Make things a ton easier to review

[6:06] 
So then

[6:07] 
even if we only have modules

[6:07] 
they still share action types

[6:07] 
because they have some way of communication

adrian [6:07 AM] 
yeah you need to have coupling at some point, but the farther up it is the better

julian [6:07 AM] 
ok

[6:08] 
I can’t think of anything more explicit than `SOMETHING_GLOBAL_IN_ALLCAPS` :smile:

adrian [6:08 AM] 
mm

julian [6:09 AM] 
the thing is

[6:09] 
if you splice the reducers by action

[6:09] 
you’re now sharing the same reducers

[6:09] 
among modules

[6:09] 
that is also coupling

[6:10] 
it’s like `shared-styles`

[6:10] 
hehe

adrian [6:10 AM] 
not entirely true

julian [6:10 AM] 
no

[6:10] 
not entirely

[6:10] 
I guess I’m having trouble visualising it

adrian [6:11 AM] 
http://www.code-experience.com/problems-with-flux/#reducersdonotsolvetheproblems talks about the approach, but basically

[6:11] 
you still define the state mutations separately

[6:11] 
but you compose them at the top level

[6:12] 
so you can have `RunState.updateRuns` and `Notifications.displaySuccess` defined separately

new messages
[6:13] 
and then in your top level reducer you do
```case TRIGGER_RUN:
  state = RunState.updateRuns(state, payload);
  state = Notifications.displaySuccess(state, payload);
  return state

``````
(edited)

julian [6:14 AM] 
ok

[6:15] 
 ```export default _.compose(
  updateRun,
  displaySuccess,
  whateverElse,
);
``````

[6:16] 
the type of freedom you get when everything is a function is great

[6:17] 
hm

[6:17] 
how about this:

adrian [6:17 AM] 
the missing bit of details is that you're gonna need to massage the data, because `displaySuccess` probably shouldn't be able to handle the payload directly

julian [6:17 AM] 
sure

[6:18] 
so how about just sharing reducers

[6:18] 
instead of making one reducer for every action

[6:18] 
seems like the lowest hanging fruit

adrian [6:18 AM] 
yeah

[6:18] 
like in your module you still define "reducers" in the sense that they return new state give the input

julian [6:18 AM] 
`libs/reducers/updateRun`

[6:20] 
and for the shared actions

[6:20] 
hm

adrian [6:21 AM] 
we don't / shouldn't do anything ​_right now_​

[6:21] 
i think it will be easier when reflux / backbone is out

julian [6:22 AM] 
what we could do is add to our best practices repo

adrian [6:22 AM] 
y

[6:22] 
well

[6:22] 
this is quite a different way of structuring things vs our current way of using redux

[6:23] 
idk if i want to have both ways present in the repo

julian [6:23 AM] 
open a pr

[6:23] 
for discussion

**Comment by prayogoa** [comment]
https://rainforest.slack.com/archives/customer/p1463974914007533

**Comment by ziahamza** [comment]
@prayogoa should we close it coz its old, and we dont have a storng need of this anymore I think?
