### ISSUE TITLE
Naming root module components index.js vs giving the file a meaningful name

### ISSUE THREAD

**Issue by jkaipr** [rainforestapp/frontend-conventions#21]
I remember @pscohn mentioning this at least once and the idea got stuck in my head. Naming root module component files `index.js` seems to get in the way when trying to search for a component by it's name. It forces us to write something in the sense of `ComponentName/index` when looking up a file in our editors.

This article goes a bit deeper into the matter https://hackernoon.com/the-100-correct-way-to-structure-a-react-app-or-why-theres-no-such-thing-3ede534ef1ed. The section `File naming` in the middle of the article is commenting on `index.js` use and offers some alternatives.

I tried one of the alternatives here https://github.com/rainforestapp/regenwald/pull/3583, `Notifications` has 2 different notifications, each with a name that fully describes what they do https://github.com/rainforestapp/regenwald/blob/2b356488811df6538b8d034c82a8c6bfb2467bb0/src/app/v2/components/Test/Notifications/index.js, so when you start searching for the component, you can find it easily. `index.js` serves as an export point for the directory instead of a root file.

As the article mentions, the app structure should serve us, it's main users, the browser gets one big js file, but we use our app structure to help us navigate it. Using `index.js` just for exports adds a bit of dancing around while creating new components, but we don't do that as often as looking up components by name and seeing their names in the tabs of our editors (Test/index.js vs Test.js if your editor is smart enough not to show just index.js when a few of those are open).

What do you think @rainforestapp/frontend ?

**Comment by AJFunk** [comment]
This isn't a big issue for me. But before you're familiar with the codebase it's a pain, and I do feel the annoyance of having five `index.js` tabs in my editor.

I like having shorter import paths, but it seems to make more sense to name the files after what they are exporting. Having an `index.js` as an export point is nice, especially if there are multiple components in that directory and I definitely support that.

If there is only one component in the directory, would we still want to have an `index.js`? It seems redundant, but it would keep our import paths consistent. But this raises the question of if it should be a default export. If so, what happens if we add another component to that directory?

**Comment by pscohn** [comment]
I totally agree @jkaipr, I was actually drafting up a note to talk about this a couple weeks back.

Some of the highlights of what I was thinking:

- when we finally refactor to start using folders for `models` and `routes`, it will not make as much sense to use `index.js` for the component, as the component won't be grouped with the actions, reducers, etc - only the components related to that route

- easier searching and selecting in code editors, as Jiri says. we could help this even more by using unique filenames depending on whether it's a spec, reducer, etc. For example, `Feature.js` - component; `Feature.spec.js` - component spec; `FeatureReducer.js` - reducer

- Facebook requires react components to all have 100% unique names with their module system. This is on the extreme end and means longer names, but it means you can quickly import a component with only the component name, and finding the files is easy. I think it would help to move a little bit in this direction, though not necessarily all the way

- using `index.js` like we do encourages index bloat - keeping everything related to component in one file - see components/Result/StepBrowsers/index.js for an example. Naming the component with its name might encourage keeping it to the one component in the filename, and for others, split it out into smaller ones.

- using `index.js` only for exporting means we spend less time in `index`, but can use it to see exactly which files are depended on externally at a glance. Also, you don't ever need to import from deeply nested components, you can access it from the top level `index`

- we can vastly reduce the number of folders in regenwald while organizing similar components together. Similar to Jiri's notification example. Every new component does not need a new folder and a new index.js - it could be grouped in the route folder, or in a component folder related to its function. I wrote this example:

```
For example, `CreateEditEnvironmentModal` contains 3 folders and 5 files: 3 `index.js`, an `index.js.snap`, and `style.css`. The folder name is great and unique, but the files inside can easily be confused with any other file in the codebase when searching, using tabs. Instead, we could rename these files `CreateEditEnvionmentModal.js` + `.spec.js`, perhaps `CreateEditEnvironmentModal.css`, and group them with like files. Perhaps `app/v2/components/SitesAndEnvironments/Environments` or `app/v2/components/modals/`.
```

So, I'm highly in favor of using `index.js` only for exporting :)

**Comment by prayogoa** [comment]
+1 for using index.js as export point only, I think this is the best of both worlds since:
- We get easily searchable components
- We still get shorter import paths


> If there is only one component in the directory, would we still want to have an index.js?

I think in this case you wouldn't create a new directory but instead just have `Component.js`

**Comment by jkaipr** [comment]
Sometimes having a directory and sometimes not having a directory leads to having two alphabetically sorted sections in the editor tree view. I think I would prefer having directories. You might want to add styles to the component at some point and in that case you would either move it to a directory or have the css files next to the js/css files of all components without directories. The directory also makes a neat place for any readme or tests that would live with it.

**Comment by prayogoa** [comment]
How would this work with actions, schemas, reducers, selectors and styles? They have the same duplicate file name problem but we already don't benefit from shorter import paths unlike the index.

Should they also be namespaced by the component name? eg. `TestActions`, `TestSchemas`, `TestReducer` etc.?

**Comment by jkaipr** [comment]
Paul wrote about it in his comment:

> - easier searching and selecting in code editors, as Jiri says. we could help this even more by using unique filenames depending on whether it's a spec, reducer, etc. For example, Feature.js - component; Feature.spec.js - component spec; FeatureReducer.js - reducer

Which gives us two options:
```
Feature.js
Feature.actions.js
Feature.reducer.js
Feature.selectors.js
Feature.schema.js
Feature.spec.js
...
```
or
```
Feature.js
FeatureActions.js
FeatureReducer.js
FeatureSelectors.js
FeatureSchema.js
FeatureSpec.js
```

Not entirely clear on the spec part for me. Paul's suggestion sounds like he would see it in the same folder as the other files (might be reading it wrong). That seems to lead to having a tree with less branches, less opening and closing of folders if you're interested in specs. On the other hand, if you have a folder with a bit more component files, each will also have a spec file next to itself, leading to quite a crowded folder, which doesn't sound too great to me. I feel like mocks should stay in a separate folder and tests probably too. But nothing prevents us from naming test like `__tests__/Feature.spec.js`.

**Comment by pscohn** [comment]
I don't think I meant for specs necessarily to be in the same folder. I'm picturing maybe something like this (including the new folders we had planned for routes/models):

```
routes/Features/index.js
routes/Features/Feature.js
routes/Features/SomeSubComp.js
routes/Features/Feature.css
routes/Features/__tests__/Feature.spec.js
routes/Features/__tests__/SomeSubComp.spec.js
routes/Features/__mocks__/Feature.mock.js

models/Features/FeatureActions.js
models/Features/FeatureReducers.js
models/Features/__tests__/FeatureActions.spec.js
models/Features/__tests__/FeatureReducers.spec.js
```

This is just one idea, but it means each file has a unique name without looking at the path at all. The specs, mocks etc can be put in whatever directories make it clean for tree browsing, I think our current system works. But for searching, I like the idea of having these unique names.

**Comment by jkaipr** [comment]
Seems good to me 👍

**Comment by pscohn** [comment]
If no one else has any comments, I'll make a PR to add to conventions and close this.

**Comment by prayogoa** [comment]
Thoughts on how we can transition the codebase to this new structure? It's going to touch literally every file under `./src`, so having a long living open giant PR might be a nightmare to both review and maintain
