### ISSUE TITLE
Proposal: WithAsyncData initate and listen to async fetching operations

### ISSUE THREAD

**Issue by ziahamza** [rainforestapp/frontend-conventions#30]
## Existing Conventions
1. `resource.isEmpty() ? <Spinner /> : <RenderData data={resource} />` Some components just need to know if data is **loaded** or not. They couple with with 
```
componentWillMount() { /* data may not be loaded, so fetch anyways */ fetchResource() }
``` 

2. Use withButtonState to know if data is stale or not. e.g we do: `state === 'pending' || !resource.isEmpty() ? <Spinner /> : <RenderData ... />`. These components care about **loaded** and it being **stale**. If either is false, then it shows a spinner otherwise. This is pretty common, when user makes some edits, and its saving. Or on pusher updates:

```
.
componentWillMount() { 
  /* data may not be loaded, so fetch anyways */
  this.props.fetchResource()
}
componentWillRecieveProps(props) { 
  /* check if data is stale, when user changes page size or some conditional changes */ 
  props.page !== this.props.page && fetchResource() 
}
onPageChange(page) {
  this.props.onPageChange(page);

  /* data incorrect now, so re-fetch */
  this.props.fetchResource();
}
onPusherUpdate() { /* data is stale, refresh */ fetchResource() }
...
``` 
These components use withButtonState to show a spinner to listen for actions which `fetch` and perhaps `save`. 

3. Sometimes the data is not only `stale`, but rather `incorrect`. E.g when the user selects a new filter, or switches to another test / feature / run. We dont really handle this case quite well e.g in the `TestList` when a user selects a new page or changes filter. The data shown is actually a mismatch, and new data is shown when it is fetched. On a slow connection this feels weird, as its not clear if its loaded yet or not (except form the top level spinner on the left)

Its a mess where the fetching / re-fetching currently lives. And very hacky to always check if props change, and manually trigger a re-fetch.

## Proposal: WithAsyncData
Have a react component that owns fetching resources, and gives props to know if its `loading`, `refreshing` or `not_available` (404, offline, errors). It would also pass down . The usage of component will look like this pending further changes:
```js
<Page>
  <WithAsyncData action={fetchRun} actionArgs={{ runId: params.runId }} fallback={runs.get(params.runId)}>
  {({ isLoading, isRefreshing, reload: refreshRun }) => (
    <Page.Content>
      <Pusher onUpdate={refreshRun} />
      { isLoading ? <Spinner /> : <RenderRun isRefreshing={isRefreshing} runId={params.runId} /> }
    </Page.Content>
  )}
  </WithAsyncData>
</Page>
```

For lists, it can optionally pass down a `data` property, which would contain the result of the action. This is useful when you want to get meta info for a list i.e the totalItems, numberOfPages, Ids of entities to be displayed on the current page. Example of that would be:

```js
<Page>
  <WithAsyncData action={fetchTests} actionArgs={filters}>
  {({ isLoading, isRefreshing, reload: refreshTests, data: { result: { totalItems, totalPages, tests } }) => (
    <Page.Content>
      <Pusher onUpdate={refreshTests} />
      { isLoading ? <Spinner /> : <TestList {...{ totalItems, totalPages, testsOnPage: tests, filters}} /> }
    </Page.Content>
  )}
  </WithAsyncData>
</Page>
```

WithAsyncData would:
- Mark data as incorrect when `actionArgs` change, so will pass `isLoading` => `true`, & `isRefreshing` => false
- When `reload` is called from child function, `isLoading` => `false` & `isRefreshing` => `true`.
-  On Mount, it would call `action` with `actionArgs` if no `fallback` is given. In this case `fallback` is passed downstream to children. It would mark data as incorrect whenever `actionArgs` further change and re-fetch again.
- On each fetch, `WithAsyncData` would store the result of the promise, and return the data downstream as well. It would also pass a handler that takes nothing and calls `action` again with `actionArgs` and trigger a refresh.

@rainforestapp/frontend

**Comment by ziahamza** [comment]
Made the implementation here, and refactored Run List view to use `WithAsyncData`: https://github.com/rainforestapp/regenwald/pull/3734

The manual fetching was completely nuked, along with the `WithButtonState` usage. IMO a lot simpler then before, but would love to get opinions on it! @rainforestapp/frontend

**Comment by jkaipr** [comment]
Thanks for working on this @ziahamza! I'm certainly voting yes for having an abstraction of this type.

There are some things that I'm not entirely settled on and would like to discuss a bit further.

 * `fallback` & `data` - `fallback` is supposed to give an alternative source of `data` if I understand it right, in case it's pointing to some part of the redux store, it will return immutable data structures, while `data` will always be the complete response payload as a plain JS object. `render` method returns one or the other depending on what's available, but it's hard to see how they can be interchangeable

 * `data` - The way I get it from the examples is, that this is mostly supposed to serve as a way to get to some response metadata, which seems fine. What worries me a little is that it can be used to access the entire response data before it goes through reducers, which might contain some transformations or additional logic. Seems to be breaking the standard 'action -> reducer -> store update -> render' cycle. Do we really need to expose the action response data through this component, or would it be enough if the component provides info about the async action status (`isLoading` & `isRefreshing`) and a handlers for re-fetching (`resetAction` & `refreshAction`)? Accessing data could be done as usually, by reading it from the store via selectors.

Might be my concerns are irrelevant, seemed worth bringing it up though, feels like it might be cleaner to keep the data part out of it. What do you think?

**Comment by ziahamza** [comment]
@jkaipr 
`data` serves two purposes. It acts as a boolean to specify if the data has been fetched or not, and if its fetched then it can serve as a way to get access to normalized API payload directly. I can turn it into a single boolean, but I think there is a strong case for getting normalized API payloads directly form the server, especially for paginated lists.

I agree that its a bit tricky to re-reconcile `fallback` with the `data`, especially as their data structures will be different and redux store data needs to be transformed to look like the normalized API payload. 
* `fallback` => `loadOnMount`. It would become a boolean, which would specify if it should fetch the item on mount or not.
