### ISSUE TITLE
Disable arrow-body-style

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#32]
I'm thinking we should disable the arrow-body-style rule for functions.

As, either one of these would be valid:

```
const someFunc = ({ prop }) => (
  <div>{prop}</div>
);
```

```
const someFunc = ({ prop }) => {
  return (
    <div>{prop}</div>
  )
};
```

To me it's mostly a matter of taste, but sometimes refactoring one to the other adds extra work, and it's annoying if I want to quickly add a log into a functional component, but have to change the style first.

Thoughts @rainforestapp/frontend?

**Comment by prayogoa** [comment]
Do you mean we should allow both styles, or should we just enforce everything to be the later?

**Comment by pscohn** [comment]
I think we should allow both styles, leave it up to the author whether or not to refactor to the implicit return.

**Comment by AJFunk** [comment]
I think allowing both is ok. I've certainly felt the annoyance of trying to add a log.

**Comment by jkaipr** [comment]
I like the brevity of arrow body function and sometimes even prefer to skip any brackets in the return part:
```js
const someFunc = ({ prop }) => <div>{prop}</div>;
```

But I have the same experience with feeling the pain when I want to add a breakpoint in dev tools or a console.log. I agree it should be left up to the author, no need to enforce it.

**Comment by prayogoa** [comment]
ok, @pscohn can you open a PR in https://github.com/rainforestapp/eslint-config-rainforest to disable this rule and make it close this issue?

**Comment by joycechau** [comment]
I think both is fine too and prefer using arrow body function only if there's no logic inside the function like: `const someFunc = () => <div>Some text that never changes</div>;`

If there's use of props or any logic at all, then I prefer having the explicit return since it's much easier to debug and also saves time when pairing.

**Comment by pscohn** [comment]
https://github.com/rainforestapp/eslint-config-rainforest/pull/12

**Comment by pscohn** [comment]
@jkaipr / @prayogoa was this deployed successfully?

**Comment by prayogoa** [comment]
The npm module was updated but we need to bump it in regenwald too

**Comment by prayogoa** [comment]
update: https://rainforest.atlassian.net/browse/RF-5828

**Comment by prayogoa** [comment]
this rule has been disabled as of https://github.com/rainforestapp/eslint-config-rainforest/pull/15
