### ISSUE TITLE
Testing Redux Sagas

### ISSUE THREAD

**Issue by AJFunk** [rainforestapp/frontend-conventions#33]
When testing Redux Sagas, we currently use two different approaches:
1) define the generator once, and then call `generator.next` once per `it` block (example: https://github.com/rainforestapp/beak/blob/develop/src/rf/sagas/__tests__/vm.js#L25)
2) redefine the generator inside of a `beforeEach` block, and then call of the `generator.next`s to proceed to the step we want to test (example: https://github.com/rainforestapp/beak/blob/develop/src/rf/sagas/__tests__/clipboard.js#L123)
---
**Pros of approach 1:** each `it` block only has a single `generator.next` call, so it's cleaner and prevents a lot of duplicated code
```
describe('a thing' () => {
  let next;
  const generator = someFunc();

  it('does something', () => {
    next = generator.next();
    expect(...);
  });

  it('does something else', () => {
    next = generator.next();
    expect(...);
  });

  it('does a third thing', () => {
    next = generator.next();
    expect(...);
  });
});
```
**Cons of approach 1:** In order to make logic "branches" we need to redefine the generator in it's own `describe` block and then call `generator.next()` (usually inside their own `it` blocks to ensure test coverage) several times to get to the code we want to test. This results in a lot of duplicated code:
```
describe('a thing' () => {
  let next;
  const generator = someFunc();

  it('does something', () => {
    next = generator.next();
    expect(...);
  });

  it('does something else', () => {
    next = generator.next();
    expect(...);
  });

  it('does a third thing', () => {
    next = generator.next(true);
    expect(...);
  });

  describe('when the second thing returns false', () => {
    const generator2 = someFunc();
    it('does something', () => {
      next = generator2.next();
      expect(...);
    });

    it('does something else', () => {
      next = generator2.next();
      expect(...);
    });

    it('handles an error in the third thing', () => {
      next = generator2.next(false);
      expect(...);
    });
  });
});
```
---
**Pros of approach 2:** making logic "branches" is more straight-forward:
```
describe('a thing' () => {
  let next, generator;
  beforeEach(() => {
    generator = someFunc();
  });

  it('does something', () => {
    next = generator.next();
    expect(...);
  });

  it('does something else', () => {
    generator.next();
    next = generator.next();
    expect(...);
  });

  it('does a third thing', () => {
    generator.next();
    generator.next();
    next = generator.next(true);
    expect(...);
  });

  describe('when the thing returns false', () => {
    it('handles the error properly', () => {
      generator.next();
      generator.next();
      next = generator.next(false);
      expect(...);
    })
  });
});
```

**Cons of approach 2:** We have to proceed through every `generator.next` step for each `it` block (demonstrated in previous example)

---
My thought is that we should use approach 1 when testing a saga that does not have logical "branches", and use approach 2 when testing sagas that do.

Currently we don't test all possible "branches" for most of these sagas. For example, this saga https://github.com/rainforestapp/beak/blob/develop/src/rf/sagas/assignment.js#L122 is tested here https://github.com/rainforestapp/beak/blob/develop/src/rf/sagas/__tests__/assignment.js#L123

We don't test what happens when either of the `if` conditions evaluate to `false`. Note that this uses approach 1, which isn't as "branch" friendly

**Comment by pscohn** [comment]
@jkaipr discussed this a while back when he was working on those clipboard specs. I think we should go with the pattern he introduced there (option 2) as they're more like unit tests than option 1. It discourages happy-path testing since instead of multiple it's covering one case, one it only covers one case, so it's more obvious that there are paths missing.

Even if there's no logic, I'd say stick with option 2 to keep it consistent and apparent that it's a unit test, and make it easier to add cases in the future.

**Comment by prayogoa** [comment]
I'm also partial to option 2, since with option 1 we will rely on the test runner executing the `it` blocks in the same order as we declare them, which isn't guaranteed.

As @pscohn mentioned, we can treat each `describe` block as a segment of the entire flow where no branching happens. Taking the original example in option 2:
```
describe('a thing' () => {
  let next, next2, generator;
  beforeEach(() => {
    generator = someFunc();
    next = generator.next();
    next2 = generator.next(); // 2 next since there are no branches
  });

  it('does a thing', () => {
    expect(next...);
  });

  it('does another thing', () => {
    expect(next2...);
  });

  describe('when the next thing returns true', () => {
     beforeEach(() => {
       next = generator.next(true);     
     });
     
     it('handles the happy path', () => {
       expect(next...);
     });
  });
  
  describe('when the next thing returns false', () => {
    beforeEach(() => {
      next = generator.next(false);
    });
    
      it('handles the error properly', () => {
        expect(...);
      });
  });
});
```

We should also encourage more composition and limiting the amount of logic a single function has. This will result in simpler tests. Eg.
A flow with 2 branches in it's longest path all implemented in a single function:
```
const fullFlow = () => {
  yield... // thing 1
  let thing6Arg;
  if () { // branch A
    yield.. // thing 2
    if () { // branch B
      thing6Arg = yield... // thing 3
    } else {
      thing6Arg = yield ... // thing 4
    }
  } else {
    thing6Arg = yield.. // thing 5
  }
  yield... // thing 6 uses thing6Arg
};
```
the test would be:
```
describe('fullFlow', () => {
  let next, next2, generator;
  beforeEach(() => {
   generator = someFunc();
   next = generator.next() // thing 1
  });
  it('does thing 1');

  describe('when branch A is true', () => {
    beforeEach(() => {
     next = generator.next(true); // thing 2
    });
    it('does thing 2');

    describe('when branch B is true', () => {
      beforeEach(() => {
       next = generator.next(true);  // thing 3
       next2 = generator.next(/* thing6Arg */); // thing 6
      });
      it('does thing 3');
      it('does thing 6');
    });

    describe('when branch B is false', () => {
      beforeEach(() => {
       next = generator.next(false);
       next2 = generator.next(/* thing6Arg */); // thing 6
      });
      it('does thing 4');
      it('does thing 6');
    });
  });
  
  describe('when branch A is false', () => {
     beforeEach(() => {
      next = generator.next(false);
      next2 = generator.next(/* thing6Arg */); // thing 6
     });
     it('does thing 5');
     it('does thing 6');
   });
}
```

Compare with:
```
const fullFlow = () => {
  yield... // thing 1
  const thing6Arg = yield call(branchA);
  yield // thing 6 uses thing6Arg
}

const branchA = (cond) => {
  if (cond) {
    yield.. // thing 2
    yield call(branchB);
  } else {
    yield.. // thing 5
  }
}

const branchB = (cond) => {
  if (cond) {
      yield... // thing 3
    } else {
      yield ... // thing 4
    }
}
```

the test becomes:
```
describe('fullFlow', () => {
  let generator, next1, next2, next3;
  beforeEach(() => { 
    generator = someFunc(); 
    next = generator.next(); // thing 1
    next2 = generator.next(); // call branchA
    next3 = generator.next(/* thing6Arg */); // thing 6;
  });
  it('does thing 1');
  it('calls branchA');
  it('does thing 6');
});

describe('branchA', () => {
  let next, next2, generator;
  describe('when cond is true', () => {
    beforeEach(() => {
     generator = branchA(true);
     next = generator.next(); // thing2
     next2 = generator.next(); // calls branchB
    });
    it('does thing 2');
    it('calls branchB');
  });
  
  describe('when cond is false', () => {
    beforeEach(() => {
     generator = branchA(false);
     next = generator.next(); // thing5
    });
    it('does thing 5');
  });
});

describe('branchB', () => {
  let next, generator;
  describe('when cond is true', () => {
    beforeEach(() => {
     generator = branchB(true);
     next = generator.next(); // thing3
    });
    it('does thing 3');
  });
  
  describe('when cond is false', () => {
    beforeEach(() => {
     generator = branchB(false);
     next = generator.next(); // thing4
    });
    it('does thing 4');
  });  
});
```
Less nesting, and we only need to assert the behaviour of `thing 6` once. The second example ended up being longer due to the boilerplate, but it can easily be shorter if the assertion in `thing 6` is just a little long.

**Comment by macocha** [comment]
Generator cloning is a solution for branches in first approach.
Just clone generator and test both paths.

**Comment by macocha** [comment]
More info here: https://redux-saga.js.org/docs/advanced/Testing.html and I'd be leaning more into testing the whole thing instead of step by stepping it.

**Comment by AJFunk** [comment]
I also noticed the clipboard saga tests name each `generator.next` call by wrapping them in their own function https://github.com/rainforestapp/beak/blob/develop/src/rf/sagas/__tests__/clipboard.js#L88

**Comment by prayogoa** [comment]
I'm leaning towards testing the full saga now, the potential complications are:
1. We might need some substantial setup to make sure all the states are correctly populated prior to running the test
2. If your saga does both `put` and `get` from the same state tree, I don't think there's a simple way to make sure the state gets updated from the `put` before the `get` is done. We basically need to emulate the store in that case.
3. Testing `take` effects means we need to set up the subscription callbacks properly

**Comment by prayogoa** [comment]
https://github.com/redux-saga/redux-saga/issues/518

**Comment by AJFunk** [comment]
I've started working on this for the VM saga, would love some feedback (https://github.com/rainforestapp/beak/pull/688)

I think overall this approach is better and results in less brittle tests. It feels similar to our regenwald specs (set up the mock store and then test the saga based on the state). It requires a bit more configuration, but I think we could also implement something similar to our `mockStoreGenerator` in regenwald to make this a bit easier.
