### ISSUE TITLE
Avoid using `componentWill`... when possible

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#36]
@rainforestapp/frontend 

See https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TLDR: We should avoid using the following lifecycle methods when possible:

```
componentWillMount
componentWillReceiveProps
componentWillUpdate
```

Eventually they will be deprecated and we will need to move off them completely. 

This may not be possible for some use cases until React implements a couple alternative methods, but in the meantime, if we need to use one of these three methods we should check this blog post and see if there's an alternative that works today.

Not sure if we should add this to conventions since it will be somewhat short-lived, but we should at least all be aware of this when using lifecycle.

**Comment by ziahamza** [comment]
The hard one to remove is most probably `componentWillReceiveProps`. Currently, I have not found a place where it can be fully removed without fundamentally changing the component hierarchy itself. And sometimes, we cant escape using it. 

So I think even if we add it to the standard, its gonna be pretty tough to not utilize it when needed. The others are however much easier to enforce and replace in the short run until we fully upgrade.
