### ISSUE TITLE
Eslint Discussion

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#37]
@rainforestapp/frontend 

See https://rainforest.atlassian.net/browse/RF-5828

Should we continue to use rainforest-eslint-config? It adds work to change and deploy eslint rules when we could just put them locally in eslintrc. As an alternative we can move regenwald to CRA's built in eslint configuration, which is pretty minimal, and use prettier for style conventions.

**Comment by prayogoa** [comment]
I vote for moving to CRA, seems like it'll be easier to maintain and it also allows us to use prettier which will eliminate any convention discussions from PRs

**Comment by prayogoa** [comment]
We will move to prettier once we're done with RF1 deprecation to minimize the code changes

**Comment by prayogoa** [comment]
We have done this
