### ISSUE TITLE
Putting "spec" in spec filenames

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#39]
I think we discussed this before but it was never made official. 

I would like to add `spec` to the spec filenames so that they have different names than the component they are testing, easier for searching and using in editors.

We could do one of:

`FeatureActions.spec.js` (I prefer and have already begun using this after thinking we decided on it)
`FeatureActionsSpec.js`

@rainforestapp/frontend

**Comment by AJFunk** [comment]
sounds good to me

**Comment by jkaipr** [comment]
I also thought we already decided to follow that rule, probably because of all the `.spec.js` files in the `models` directory. I picked it up since noticing these and am trying to do it with new files. So yeah, sounds good to me too.

**Comment by prayogoa** [comment]
Yeah we did agree to it, the ones without `spec` in the file names are leggacy

**Comment by pscohn** [comment]
Sounds good, I'll make a PR to add it to the docs officially

**Comment by prayogoa** [comment]
#40
