### ISSUE TITLE
Ternary expectations

### ISSUE THREAD

**Issue by racpa** [rainforestapp/frontend-conventions#42]
For ternaries we mix our expectations at times, sometimes we have 

`condition ? null : data`

other times

`condition ? data : null`
I prefer the latter, when the falsy would equate to be values that are _undefined_ or less desirable

**Comment by prayogoa** [comment]
I'm not sure if it's possible to have a convention for this, consider
```
isReadOnly ? null : EditButton
```
Let's say `isReadOnly` is more aligned with how we model our data, having an attribute in the model to mark an entity as read only or not.

To follow the proposed convention, you'll need to do
```
const isEditable = !isReadOnly;
isEditable ? EditButton : null // is this better? Imo it's less intuitive since it's not directly aligned with the model

!isReadOnly ? EditButton : null // a simple negation, maybe it's worth doing?
```
Either way it's more work, albeit not by much.

Is this worth doing?
