### ISSUE TITLE
Git Merging

### ISSUE THREAD

**Issue by racpa** [rainforestapp/frontend-conventions#45]
Since we got rid of the changelog, did we want to modify our process to have a linear line of commits for each PR, so a branch's commits will stick together and stack vs being mixed via the dates of the commits on merged branches.

Proposal: rebasing our commits to `develop` and just merging into `master`

Downside: Can lead to mistakes via github if you don't change the merge button for the correct action to take.  Which is what I did during my incident in the past.

**Comment by AJFunk** [comment]
Personally I prefer to squash and merge. Github gives you that option so no need to do any manual git work, and it basically accomplishes the same thing (1 commit per PR) but without the rebasing risks.

**Comment by prayogoa** [comment]
We decided that team members should use their best judgement as to what method would lead to cleaner commits
