### ISSUE TITLE
Discussion on classnames & css customization

### ISSUE THREAD

**Issue by pscohn** [rainforestapp/frontend-conventions#46]
I think part of the team has discussed this but we haven't brought to broader discussion and made a convention, and I've seen some questions around this.

In the past we've typically done this to customize css:

` <div className={classnames(props.className, styles.className)}></div>`

The problem with that is it can result in undefined behavior - when you have to class names applied and they have conflicting properties, the one defined later in the resulting css wins. 

A solution we've talked about is to only ever apply one general class name:

 `<div className={props.className || styles.className}></div>`

In this case, if you only want to override one property of `styles.className`, then the css class where `props.className` is defined needs to import and compose what it needs from `styles.className`, and inside `styles` you can split out the more general styles:

```
styles.css:

.classNameBase {
  /* basic styles used for all instances */
}

.className {
  composes: classNameBase;
  /* more specific rules */
}

--
some parent component.css:

@value classNameBase from '../some/component';
.thisComponent {
  composes: classNameBase;
  /* different specific rules here */
}
```

This means the composing is done in the actual css, and the rendered element only needs to know about one class name. However it's still ok to apply some conditional classes as needed, as long as they don't conflict with the main class (not sure if this is the best example):

```
<div className={classnames(props.className || styles.className},
{
  [styles.editing]: isEditing,
  [styles.notEditing]: !isEditing,
}
)></div>
```

Additionally, we talked about moving a lot of the customization to props. Things like positioning should be easily modifiable by any component that wants to use some UI component, but it can be quite painful to have to define a class and compose styles just to do add some margin or change a color. So in general reusable/UI components should take in props for margin, color, size, whatever is relevant, and then use `propsToClassname` to convert them into classes. This way, you can simply do this:

```
const SomeUiComponent = ({
  color = 'blue',
  size = 'small',
  margin = 'small',
  className = styles.className
}) => <div 
        className={classnames(
          className,
          propsToClassnames({ color, size })
       )}
/>

---

// render component with custom styles
<SomeUiComponent size="large" color="red" />
```

See the implementation in https://github.com/rainforestapp/regenwald/blob/develop/src/app/utilities/style.js

Any comments, 👍 / 👎 ?

**Comment by ziahamza** [comment]
I agree that composing / overriding on top of default styes is super painful right now (without those !important hacks.

CSS modules composition sounds sane 👍

**Comment by AJFunk** [comment]
I'm on board with this 👍

**Comment by pscohn** [comment]
One thought I just had is we should consider whether we will try to make our component library a standalone package, and maybe try to adopt a convention that will work well in that case. I'm not sure how well customizing component through importing/composing css classes will work.

I looked up some component libraries and found react-toolbox uses css modules internally, and interestingly it also uses `classnames` to combine its internal class + a user provided one: https://github.com/react-toolbox/react-toolbox/blob/dev/components/avatar/Avatar.js - though I saw a couple examples that used the `style` prop as well

**Comment by prayogoa** [comment]
From their docs: https://github.com/react-toolbox/react-toolbox#customizing-components
They rely on the fact that the bundled default css will be defined first before the app defined css, so the priority will be correct.

If we want to follow this method we'll also need to endure the css order
